coreutils: Bump version to 8.30
Among other things this is required to build aginst Glibc 2.28+,
see:
https://github.com/coreutils/gnulib/commit/4af4a4a71827c0bc5e0ec67af23edef4f15cee8e

Otherwise it fails on build like that:
----------------------->8------------------------
  CC       lib/fts.o
lib/freadptr.c: In function 'freadptr':
lib/freadptr.c:119:3: error: #error "Please port gnulib freadptr.c to your platform! Look at the definition of fflush, fread, getc, getc_unlocked on your system, then report this to bug-gnulib."
 #error "Please port gnulib freadptr.c to your platform! Look at the definition of fflush, fread, getc, getc_unlocked on your system, then report this to bug-gnulib."
  ^~~~~
----------------------->8------------------------

Signed-off-by: Alexey Brodkin <abrodkin@synopsys.com>